[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer']

[phases.install]
cmds = ['cd backend && composer update --no-dev --optimize-autoloader --no-interaction']

[phases.build]
cmds = [
  'cd backend && php artisan config:cache',
  'cd backend && php artisan route:cache', 
  'cd backend && php artisan view:cache',
  'cd backend && php artisan storage:link'
]

[start]
cmd = 'cd backend && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT'
