[variables]
COMPOSER_ALLOW_SUPERUSER = '1'

[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'php82Extensions.redis']

[phases.install]
cmds = [
  'cd backend && mkdir -p bootstrap/cache storage/framework/sessions storage/framework/views storage/framework/cache storage/logs resources/views',
  'cd backend && chmod -R 775 bootstrap/cache storage',
  'cd backend && composer update --no-dev --optimize-autoloader --no-interaction'
]

[phases.build]
cmds = [
  'cd backend && php artisan config:cache',
  'cd backend && php artisan route:cache'
]

[start]
cmd = 'cd backend && php artisan serve --host=0.0.0.0 --port=$PORT'
