services:
  - type: web
    name: artitrack-backend
    runtime: docker
    plan: free
    rootDir: backend
    dockerfilePath: ./Dockerfile
    buildCommand: docker build -t artitrack-backend .
    startCommand: docker run -p $PORT:80 artitrack-backend
    envVars:
      - key: APP_KEY
        value: base64:8B7mQqM2vX9pL4nR6sT1uY3wZ5aE8fG2hJ4kL7mN9pQ=
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: SESSION_SAME_SITE
        value: none
      - key: SESSION_SECURE_COOKIE
        value: true
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: database/database.sqlite
    healthCheckPath: /
